PL/Models/ErrorViewModel.cs
namespace PL.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PL/Controllers/CopysController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class CopysController : Controller
    {
        public ActionResult GetAll()
        {
            ML.Copys copys = new ML.Copys();
            ML.Result result = BL.Copys.GetAll();

            if (result.Correct)
            {
                copys.Copies = result.Objects.ToList();
                return View(copys);
            }
            else
            {
                ViewBag.Message = "OCURRIO UN ERROR AL OBTENER LA INFORMACIÓN " + result.ErrorMessage;
                return PartialView("Modal");
            }
;
        }

        [HttpGet]
        public ActionResult Form(int Id)
        {
            ML.Copys copys = new ML.Copys();
            ML.Result resultcategory = BL.Categories.GetAll();

            copys.Categories = new ML.Categories();
            copys.Categories.categories = resultcategory.Objects.ToList();

            if (Id == 0)
            {
                copys.Action = "Add";
                return View(copys);
            }
            else
            {
                copys.Action = "Update";
                ML.Result result = BL.Copys.GetById(Id);
                if (result.Correct)
                {
                    copys = (ML.Copys)result.Object;
                    copys.Categories.categories = resultcategory.Objects.ToList();
                    return View(copys);
                }
                return View();
            }
        }
        [HttpPost]
        public ActionResult Form (ML.Copys copys)
        {
            IFormFile file = Request.Form.Files["IFImagen"];

           
            if (file != null)
            {
                byte[] ImagenBytes = ConvertToBytes(file);
                copys.File = Convert.ToBase64String(ImagenBytes);
            }
            if (copys.Action == "Add")
            {
                ML.Result result = BL.Copys.Add(copys);
                if (result.Correct)
                {
                    ViewBag.Message = "SE INSERTO CORRECTAMENTE ";
                    return PartialView("Modal");
                }
                else
                {
                    ViewBag.Message = "OCURRIO UN ERROR AL INSERTAR " + result.ErrorMessage;
                    return PartialView("Modal");
                }
            }
            else
            {
                ML.Result result = BL.Copys.Update(copys);
                if (result.Correct)
                {
                    ViewBag.Message = "SE ACTUALIZO CORRECTAMENTE ";
                    return PartialView("Modal");
                }
                else
                {
                    ViewBag.Message = "OCURRIO UN ERROR AL ACTUALIZAR " + result.ErrorMessage;
                    return PartialView("Modal");
                }
            }
            return View();
        }
        [HttpGet]
        public ActionResult Delete(int Id)
        {
            ML.Result resultcopys = new ML.Result();
            ML.Copys copys = new ML.Copys();
            copys.Id = Id;
            var result = BL.Copys.Delete(copys);

            if (result.Correct)
            {
                ViewBag.Message = "SE ELIMINIO CORRECTAMENTE EL REGISTRO";
            }
            else
            {
                ViewBag.Message = "OCURRIO UN PROBLEMA AL ELIMINAR EL USUSARIO " + result.ErrorMessage;
            }
            return PartialView("Modal");
        }
        public static byte[] ConvertToBytes(IFormFile imagen)
        {

            using var fileStream = imagen.OpenReadStream();

            byte[] bytes = new byte[fileStream.Length];
            fileStream.Read(bytes, 0, (int)fileStream.Length);

            return bytes;
        }
    }
}

PL/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PL.Models;
using System.Diagnostics;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PL/Views/Copys/Form.cshtml
@model ML.Copys
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3>@ViewBag.Titulo </h3>
                 <h2>COPYS </h2>
                <h5>Ingrese los datos </h5>
                </hr>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Copys", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="row">
                    @Html.HiddenFor(model => model.Action)
                    <div class="col-md-3">
                        @Html.LabelFor(model => model.Id, new { @class = "control-label col-md2 " })
                        @Html.TextBoxFor(model => model.Id, new { @class = "form-control" })
                    </div>
                    <div class="col-md-3">
                        @Html.LabelFor(model => model.Medio, new { @class = "control-label col-md2 " })
                        @Html.TextBoxFor(model => model.Medio, new { @class = "form-control" })
                    </div>
                    <div class="col-md-3">
                        @Html.LabelFor(model => model.Fecha, new { @class = "control-label col-md2 " })
                        @Html.TextBoxFor(model => model.Fecha, new { @class = "form-control", @id = "txtFechaNacimiento" })
                    </div>
                    <div class="col-md-3">
                        @Html.LabelFor(model => model.Marca, new { @class = "control-label col-md2 " })
                        @Html.TextBoxFor(model => model.Marca, new { @class = "form-control" })
                    </div>
                    <div class="col-md-3">
                        @Html.LabelFor(model => model.Producto, new { @class = "control-label col-md2 " })
                        @Html.TextBoxFor(model => model.Producto, new { @class = "form-control" })
                    </div>
                    <div class="col-md-3">
                        @Html.LabelFor(model => model.Version, new { @class = "control-label col-md2 " })
                        @Html.TextBoxFor(model => model.Version, new { @class = "form-control" })
                    </div>

                    <div class="col-md-3">
                        @Html.LabelFor(model => model.Vehiculo, new { @class = "control-label col-md2 " })
                        @Html.TextBoxFor(model => model.Vehiculo, new { @class = "form-control"})
                    </div>
                    <div class="col-md-3">
                        @Html.LabelFor(model => model.Anunciante, new { @class = "control-label col-md2 " })
                        @Html.TextBoxFor(model => model.Anunciante, new { @class = "form-control"})
                    </div>
                    <div class="col-md-3">
                        @Html.LabelFor(model => model.Tema, new { @class = "control-label col-md2 " })
                        @Html.TextBoxFor(model => model.Tema, new { @class = "form-control"})
                    </div>
                    <div class="col-md-3">
                        @Html.LabelFor(model => model.Categories, new { @class = "control-label col-md2 " })
                        @Html.DropDownListFor(model => model.Categories.Id, new SelectList(Model.Categories.categories, "Id", "Name"), "Selecciona una opcion", new { @class = "form-control"})
                    </div>

                    <div class="col-md-4">
                        @Html.LabelFor(model => model.Processing)
                        <br />
                        True
                        @Html.RadioButtonFor(model => model.Processing, "True")
                        False
                        @Html.RadioButtonFor(model => model.Processing, "False")
                    </div>

                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model=> model.File)

                            <div class="input-group mb-3">
                                <input id="IFImagen" type='file' class="form-control" name="IFImagen" onchange="validateFile(this), readURL(this);  " />
                            </div>
                            @if (Model.File != null)
                            {

                                <img id="Img" src="data:image/*;base64,@Model.File" style="width:200px ; height:200px" />

                            }
                            else
                            {
                                <img id="Img" src="~/Imagenes/sinProducto.png" style="width:200px ; height:200px" />
                            }
                        </div>
                        @Html.HiddenFor(model => model.File)
                    </div>

                    <div class="form-group">
                        <div class=" col-md-3">

                            <input type="submit" value="Guardar" class="btn btn-success" />
                            @Html.ActionLink("Regresar", "GetAll", "Copys", htmlAttributes: new { @class = "btn btn-danger" })
                        </div>
                    </div>
                </div>
            }

        </div>

    </div>

    @section Scripts
    {
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>


    <script type="text/javascript">
                $( function() {
          $( "#txtFechaNacimiento" ).datepicker({dateFormat: 'dd-mm-yy',
                                      changeMonth: true,
                                      changeYear: true});
        } );


                function validateFile()
                   {
                       var allowedExtension = ['jpeg', 'jpg','png'];
                       var fileExtension = document.getElementById('IFImagen').value.split('.').pop().toLowerCase();
                       var isValidFile = false;
                           for(var index in allowedExtension) {
                               if(fileExtension === allowedExtension[index]) {
                                   isValidFile = true;
                                   break;
                               }
                           }
                           if(!isValidFile) {
                               alert('Las extensiones permitidas son : *.' + allowedExtension.join(', *.'));
                               document.getElementById('IFImagen').value = ""
                           }
                           return isValidFile;
                   }
                    function readURL(input) {
                    if (input.files && input.files[0]) {
                        var reader = new FileReader();
                        reader.onload = function (e) {
                            $('#Img')
                              .attr('src', e.target.result);
                        };
                        reader.readAsDataURL(input.files[0]);
                    }
                }

    </script>

    }

PL/Views/Copys/GetAll.cshtml
@model ML.Copys
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <h2> PRODUCTOS </h2>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h5>Seleccione el producto para editarla o el botón de + para agregar un nuevo producto</h5>
            <hr />
        </div>
    </div>



    <div style="float:right;">
        @Html.ActionLink("+", "Form", "Producto", htmlAttributes: new { @class = "btn btn-success" })
    </div>
    @if (Model.Copies == null)
    {
        <div class="p-3 mb-2 bg-danger text-withe"> Aun no hay registros registardos</div>

    }
    else
    {
        <table class=" table table-bordered table-responsive">
            <thead>
                <tr>
                    <td class=" text-center"> Editar </td>

                    <td class="d-lg-none">Id</td>
                    <td class="text-center">Medio</td>
                    <td class="text-center">Fecha</td>
                    <td class="text-center">Marca</td>
                    <td class="text-center">Producto</td>
                    <td class="text-center">Version</td>
                    <td class="text-center">Vehiculo</td>
                    <td class="text-center">Anunciante</td>
                    <td class="text-center">Tema</td>
                    <td class="d-lg-none">Id_Category</td>
                    <td class="text-center">Category</td>
                    <td class="text-center">Processing</td>
                    <td class="text-center">File</td>


                    <td class="text-center">Eliminar</td>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.Copys copys in Model.Copies)
                {
                    <tr>
                        <td class="text-center"><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Form","Copys",new { Id= copys.Id })"><i class="bi bi-pencil-square"></i></a></td>

                        <td class="d-lg-none">@copys.Id</td>
                        <td class="text-center">@copys.Medio</td>
                        <td class="text-center">@copys.Fecha</td>
                        <td class="text-center">@copys.Marca</td>
                        <td class="text-center">@copys.Producto</td>
                        <td class="text-center">@copys.Version</td>
                        <td class="text-center">@copys.Vehiculo</td>
                        <td class="text-center">@copys.Anunciante</td>
                        <td class="text-center">@copys.Tema</td>
                        <td class="d-lg-none">@copys.Categories.Id</td>
                        <td class="text-center">@copys.Categories.Name</td>
                        <td class="text-center">@copys.Processing</td>
                        <td class="text-center">
                            @if (copys.File != "")
                            {

                                <img id="Img" src="data:image/*;base64,@copys.File" style="width:80px ; height:80px" />

                            }
                            else
                            {
                                <img id="Img" src="~/Imagenes/sinProducto.png" style="width:80px ; height:80px" />
                            }
                        </td>

                        <td class="text-center"><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Copys", new { Id = copys.Id})" onclick="return confirm('Estas seguro que deseas eliminar este producto?');"><i class="bi bi-eraser-fill"></i></a></td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

PL/Views/Copys/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Copys", htmlAttributes: new { @class = "btn btn-danger" })


            </div>
        </div>
    </div>
</div>

<script>
    $('#Modal').modal();
</script>

PL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PL.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Copys" asp-action="GetAll">Copys</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>